language: java
jdk:
 - oraclejdk8
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
env:
- BLOG_DB_URL=$BLOG_DB_URL
- BLOG_DB_USER=$BLOG_DB_USER
- BLOG_DB_PASSWORD=$BLOG_DB_PASSWORD
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: first-blog-site
